name: backend

environment:
  sdk: '^3.2.0'
dependencies:
  shelf: ^1.1.3
  shelf_router: ^1.1.1
  shelf_static: ^1.1.0
  firedart: ^0.9.7
  shelf_multipart: ^1.0.0
  redis: ^4.0.0
  cloud_firestore: ^4.15.5
  googleapis: ^13.1.0
  googleapis_auth: ^1.5.0
  dio: ^5.4.1
  cached: ^1.7.0
